import regex as re
from typing import List, Dict, Tuple, Optional, Iterable
from functools import lru_cache
import os
import json
import numpy as np

PAT = r"""'(?:[sdmt]|ll|ve|re)| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+"""

class Tokenizer:

    def __init__(
        self,
        vocab: Dict[int, bytes],
        merges: List[Tuple[bytes, bytes]],
        special_tokens: Optional[List[str]] = None,
    ):
        """
        Construct a BPE tokenizer.
        
        Args:
            vocab: A dictionary mapping token IDs to their byte representations.
            merges: A list of tuples representing BPE merge operations.
            special_tokens: Optional list of strings that should be treated as unbreakable tokens.
        """
        self.vocab: Dict[int, bytes] = vocab
        self.token_encode: Dict[bytes, int] = {v: k for k, v in vocab.items()}
        self.merges: List[Tuple[bytes, bytes]] = merges
        self.bpe_ranks: Dict[Tuple[bytes, bytes], int] = dict(zip(merges, range(len(merges))))
        self.pat = re.compile(PAT)

        self.special_tokens: List[str] = special_tokens or []
        self.special_token_bytes: List[bytes] = [token.encode("utf-8") for token in self.special_tokens]

        for token_bytes in self.special_token_bytes:
            if token_bytes not in self.token_encode:
                # Add to vocab if not already present
                new_id = len(self.vocab)
                self.vocab[new_id] = token_bytes
                self.token_encode[token_bytes] = new_id

        if self.special_tokens:
            sorted_special = sorted(self.special_tokens, key=len, reverse=True)
            pattern = "|".join(map(re.escape, sorted_special))
            self.special_token_pattern = re.compile(f"({pattern})")
        else:
            self.special_token_pattern = None

    def encode(self, text: str) -> List[int]:
        """
        Encode an input text string into a sequence of token IDs.
        
        Args:
            text: The input text to encode.
            
        Returns:
            A list of integer token IDs representing the encoded text.
        """
        tokens: List[int] = []

        if self.special_token_pattern:
            # Split the text by special tokens
            segments = self.special_token_pattern.split(text)
        else:
            segments = [text]

        for seg in segments:
            if seg is None or seg == '':
                continue
            if seg in self.special_tokens:
                # If it's a special token, add its ID directly
                tokens.append(self.token_encode[seg.encode("utf-8")])
            else:
                # Otherwise, tokenize normally
                for m in self.pat.finditer(seg):
                    word_bytes = m.group(0).encode("utf-8")
                    byte_tuple = tuple(bytes([b]) for b in word_bytes)
                    merged_bytes = self._bpe_merges(byte_tuple)
                    tokens.extend(self.token_encode[b] for b in merged_bytes)
        return tokens

    def encode_iterable(self, iterable: Iterable[str]) -> Iterable[int]:
        """
        Given an iterable of strings (e.g., a file handle), yield token IDs lazily.
        
        Args:
            iterable: An iterable source of text chunks.
            
        Yields:
            Token IDs generated by processing the input iterable.
        """
        for chunk in iterable:
            yield from self.encode(chunk)

    def decode(self, ids: List[int]) -> str:
        """
        Decode a sequence of token IDs back into a readable string.
        
        Args:
            ids: A list of integer token IDs.
            
        Returns:
            The decoded string representation of the input token IDs.
        """
        full_bytes = b"".join(self.vocab.get(token_id, b'') for token_id in ids)
        return full_bytes.decode("utf-8", errors="replace")

    def _bpe_merges(self, byte_tuple: Tuple[bytes, ...]) -> List[bytes]:
        """
        Apply BPE merges to a sequence of bytes.
        
        Args:
            byte_tuple: A tuple of single-byte tokens (e.g., (b'H', b'e', b'l', b'l', b'o')).
            
        Returns:
            A list of merged byte tokens after applying all applicable merges.
        """
        word: List[bytes] = list(byte_tuple)

        def get_pairs(word_list: List[bytes]) -> set:
            return set(zip(word_list, word_list[1:]))
        pairs = get_pairs(word)

        if not pairs:
            return word

        while True:
            best_merge = min(pairs, key=lambda pair: self.bpe_ranks.get(pair, float('inf')))
            
            if best_merge not in self.bpe_ranks:
                break
            
            first, second = best_merge
            new_word: List[bytes] = []
            idx = 0
            
            while idx < len(word):
                if idx < len(word) - 1 and word[idx] == first and word[idx + 1] == second:
                    new_word.append(first + second)
                    idx += 2
                else:
                    new_word.append(word[idx])
                    idx += 1
            word = new_word
            if len(word) == 1:
                break

            pairs = get_pairs(word)

        return word
    
    @classmethod
    def from_files(
        cls, 
        vocab_filepath: str, 
        merges_filepath: str, 
        special_tokens: Optional[List[str]] = None
    ) -> "Tokenizer":
        """
        Constructs a Tokenizer from GPT-2-style vocab and merge files.

        Args:
            vocab_filepath: Path to the .json vocab file (e.g., gpt2_vocab.json)
            merges_filepath: Path to the .bpe merges file (e.g., gpt2_merges.txt)
            special_tokens: Optional list of special token strings.

        Returns:
            A new Tokenizer instance.
        """
        bs = list(range(ord("!"), ord("~")+1)) + \
             list(range(ord("¡"), ord("¬")+1)) + \
             list(range(ord("®"), ord("ÿ")+1))
        cs = bs[:]
        n = 0
        for b in range(2**8):
            if b not in bs:
                bs.append(b)
                cs.append(2**8 + n)
                n += 1
        byte_to_char_map = {b: chr(c) for b, c in zip(bs, cs)}
        char_to_byte_map = {c: b for b, c in byte_to_char_map.items()}

        try:
            with open(vocab_filepath, 'r', encoding='utf-8') as f:
                vocab_json = json.load(f)
            
            inverted_vocab_str = {id: token_str for token_str, id in vocab_json.items()}
            vocab = {}
            for id, token_str in inverted_vocab_str.items():
                token_bytes = b"".join(bytes([char_to_byte_map[c]]) for c in token_str)
                vocab[id] = token_bytes

        except Exception as e:
            print(f"Error loading vocab file {vocab_filepath}: {e}")
            raise

        merges = []
        try:
            with open(merges_filepath, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    
                    part1, part2 = line.split()

                    b1 = b"".join(bytes([char_to_byte_map[c]]) for c in part1)
                    b2 = b"".join(bytes([char_to_byte_map[c]]) for c in part2)
                    merges.append((b1, b2))
        except Exception as e:
            print(f"Error loading merges file {merges_filepath}: {e}")
            raise

        return cls(vocab=vocab, merges=merges, special_tokens=special_tokens)

def main():

    print("Loading tokenizer...")
    # vocab = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/tests/fixtures/gpt2_vocab.json"
    # merges = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/tests/fixtures/gpt2_merges.txt"
    vocab = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/trained_vocab.json"
    merges = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/trained_merges.txt"
    # txt_train_file = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/TinyStoriesV2-GPT4-valid.txt"
    txt_train_file = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/TinyStoriesV2-GPT4-valid.txt"
    # txt_valid_file = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/TinyStoriesV2-GPT4-valid.txt"
    npy_train_file = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/TinyStoriesV2-GPT4-valid.npy"
    # npy_valid_file = "/mnt/nfs_project_a/yichen/NLPDL-2025Fall/hw1_bpe_and_lm/data/TinyStoriesV2-GPT4-valid.npy"
    special_tokens = ["<|endoftext|>"]
    tokenizer = Tokenizer.from_files(vocab, merges, special_tokens)

    print(f"Loading and encoding {txt_train_file}...")
    with open(txt_train_file, 'r', encoding='utf-8') as f:
        text = f.read()
    
    tokens = tokenizer.encode(text)
    
    token_array = np.array(tokens, dtype=np.uint16)
    
    print(f"Total tokens: {len(token_array)}")
    print(f"Saving to {npy_train_file}...")
    np.save(npy_train_file, token_array)


if __name__ == "__main__":
    main()